config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  resources :comments
  post "new_user_like", to: "likes#new_user_like"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true

  validates :kind, acceptance: {
    accept: %w[like dislike]
  }
  def self.kinds
    %w[like dislike]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users, through: :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, through: :likes
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show destroy ] 
  before_action :redirect_request, only: %i[edit update destroy]
  
  # GET /comments/1 or /comments/1.json
  def show
  end
  
  # GET /comments/new
  def new
    @comment = Comment.new
  end
  
  # GET /comments/1/edit
  def edit
  end
  
  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    if user_signed_in?
      @comment.user = current_user
    end
    respond_to do |format|
      if @comment.save
        format.html { redirect_to comments_url(@comment), notice: "Tú comentario fue creado con éxito." }
      else
          format.html { redirect_to comments_url(@comment), notice: "No se pudo crear tú comentario" }
        end
      end
    end
  
    # DELETE /comments/1 or /comments/1.json
    def destroy
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to comments_url(@comment), notice: "Tú comentario fue eliminado con éxito" }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_comment
        @comment = Comment.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def comment_params
        params.require(:comment).permit(:content, :user_id, :post_id )
      end
      def redirect_request
        if current_user.id != @comment.user_id
          redirect_to comments_url(@comment), notice: "No puedes hacer eso pillin"
        end
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!

    def new_user_like
        @user = current_user
        @post = Post.find(params[:post_id])
        like = Like.find_by(user_id: @user.id, post_id: @post.id)
        if like
            return flash.now[:alert] = "Ya Has reaccionado a este post"
        else
            @new_like = Like.new(user_id: @user.id, post_id: @post.id, kind: params[:kind])
            respond_to do |format|
                if @new_like.save!
                    format.html {redirect_to post_url(@post), notice: "Acabas de reaccionar satisfactoriamente"}
                else
                    format.html {redirect_to post_url(@post), status: :unprocessable_entity}
                end
            end
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    comment = Comment.new
    comment = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:image, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comentarios.html.erb
<div class="card comments mt-3 mb-2 bg-dark text-light">
  <div class="card-header border-bottom-0 font-weight-bold bg-transparent">Comentarios</div>
  <ul class="list-group list-group-flush">
    <% @post.comments.each do |comment| %>
      <li class="list-group-item bg-dark text-light">
        <header class="comment-header"><strong><i class="fa-solid fa-cat fa-xl" style="color: #930606;">
        </i><%= (comment.user.name if comment.user) || "Anonymous" %></strong> wrote <%= distance_of_time_in_words(Time.current, comment.created_at) %> ago</header>
        <div class="comment-body"><strong><%= comment.content %></strong></div>
        <% if user_signed_in? %>
            <%= button_to "Eliminar comentario", comment, method: :delete, class:"btn button3" %>
        <% end %>
      </li>
    <% end %>

    <% if @post.comments.empty? %>
      <li class="list-group-item text-center">Aún no hay comentarios para este post </li>
    <% end %>
  </ul>
</div>
    <div class="card bg-dark new-comment">
      <div class="card-body">
        <p><strong class="text-light">Deja tu comentario:</strong></p>
        
        <%= form_for @post.comments.build do |f| %>
          <%= f.hidden_field :post_id, value: @post.id %>
  <div>
      <%= f.label :content, style: "display: block" %>
      <%= f.text_field :content, class:"form-control" %>
    </div>

          <div class="text-right">
            <%= f.submit "Comentar", class: "btn button3 my-3" %>
          </div>
          <div>
          <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar/navbar" %>
    <%= yield %>
    <script src="https://kit.fontawesome.com/4e081be960.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark text-light" data-bs-theme="dark">
  <div class="container">
    <%= link_to "Crazy4Cats", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
              <% if current_user.name %>
                Hola <%= current_user.name %>
              <% else %>
                Hola <%= current_user.email %>
              <% end %>
            <% else %>
                Inicia sesión o registrate
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= button_to "Cerrar Sesión", destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
            <% else %>
                <li><%= link_to "Iniciar Sesión", new_user_session_path, class:"dropdown-item" %></li>
                <li><%= link_to "Registro", new_user_registration_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/likes/_reactions.html.erb
<div class="container p-2 text-center text-light">
<i class="fa-regular fa-thumbs-up fa-xl"></i>
<% Like.kinds.each do |kind| %>
  <%= @post.likes.where(kind: kind).count %> |
 <% end %>
 <i class="fa-regular fa-thumbs-down fa-xl "></i>
<div class="d-flex justify-content-center">

 <% Like.kinds.each do |kind| %>
 <%= button_to "#{kind.capitalize}", new_user_like_path(post_id: @post.id, kind: kind), class:"btn button3 mx-1", method: :post %> 
 <% end %>
 
</div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="bg-dark p-3 text-light">
    <p>
      <%= image_tag post.image, class: "photo" %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= post.description %>
    </p>

    <p>
      <strong>User:</strong>
      <%= post.user.name %>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="bg-dark p-3 text-light">
  <h1>Editing post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Show this post", @post, class: "btn btn-secondary" %> |
    <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  
    <% @posts.each do |post| %>
    <div class="d-flex justify-content-center">
      <%= render post %>
    </div>
    <p class="text-center mt-2">
      <%= link_to "Show this post", post, class:"btn button3" %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path, class: "btn submit" %>

app/views/posts/new.html.erb
<div class="bg-dark p-3 text-light">
  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-center">
  <%= render @post %>
</div>
<div class="m-3 d-flex justify-content-center">
  <%= link_to "Back to posts", posts_path, class:"btn button3" %>
</div>
  <%= render 'likes/reactions' %>

<div class="container">
  <%= render 'comments/comentarios' %>
</div>
<% if user_signed_in? %>
    <% if current_user.id == @post.user_id %>
      <div class="d-flex justify-content-center">
        <%= link_to "Edit this post", edit_post_path(@post), class:"btn button3 mx-3" %>
        <%= button_to "Destroy this post", @post, method: :delete, class: "btn button3" %>
      </div>
    <% end %>
  <% end %>